# 1. Lightgbm

* 데이터 '와인품질분류.zip'입니다.

1. 필요한 라이브러리를 가져옵니다.

In [1]:
import pandas as pd
import lightgbm as lgbm

2. 데이터를 불러옵니다.

In [2]:
train = pd.read_csv('/Users/seomichelle/26-1 ESAA:Python/datasets/와인품질분류/train.csv')
test = pd.read_csv('/Users/seomichelle/26-1 ESAA:Python/datasets/와인품질분류/test.csv')
smpl_sub = pd.read_csv('/Users/seomichelle/26-1 ESAA:Python/datasets/와인품질분류/sample_submission.csv')

In [3]:
train.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

In [4]:
test.head()

,index,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,9.0,0.31,0.48,6.6,0.043,11.0,73.0,0.99380,2.90,0.38,11.6,white
1,1,13.3,0.43,0.58,1.9,0.070,15.0,40.0,1.00040,3.06,0.49,9.0,red
2,2,6.5,0.28,0.27,5.2,0.040,44.0,179.0,0.99480,3.19,0.69,9.4,white
3,3,7.2,0.15,0.39,1.8,0.043,21.0,159.0,0.99480,3.52,0.47,10.0,white
4,4,6.8,0.26,0.26,2.0,0.019,23.5,72.0,0.99041,3.16,0.47,11.8,white

3. 변수를 변환합니다.

In [5]:
# type에는 white와 red 두 종류가 있습니다.
# 각각 0,1로 변환합니다.
train['type'] = train['type'].map({'white':0, 'red':1}).astype(int)
test['type'] = test['type'].map({'white':0, 'red':1}).astype(int)

In [6]:
train.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,0
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,1
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,0
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,0
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,0

In [7]:
test.head()

,index,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,9.0,0.31,0.48,6.6,0.043,11.0,73.0,0.99380,2.90,0.38,11.6,0
1,1,13.3,0.43,0.58,1.9,0.070,15.0,40.0,1.00040,3.06,0.49,9.0,1
2,2,6.5,0.28,0.27,5.2,0.040,44.0,179.0,0.99480,3.19,0.69,9.4,0
3,3,7.2,0.15,0.39,1.8,0.043,21.0,159.0,0.99480,3.52,0.47,10.0,0
4,4,6.8,0.26,0.26,2.0,0.019,23.5,72.0,0.99041,3.16,0.47,11.8,0

In [8]:
# 모델에 입력하기 전 데이터를 정형합니다.
# train_x : train의 'index', 'quality' 피처를 제거하고 저장합니다.
# train_y : train의 'quality'를 저장합니다.
# test_x : test의 'index'를 제거하고 저장합니다.

train_x = train.drop(['index', 'quality'], axis = 1)
train_y = train['quality']
test_x = test.drop('index', axis = 1)

In [9]:
train_x.shape, train_y.shape, test_x.shape

((5497, 12), (5497,), (1000, 12))

In [10]:
train_x.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,0
1,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,1
2,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,0
3,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,0
4,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,0

In [11]:
train_y.head()

0    5
1    5
2    5
3    6
4    6
Name: quality, dtype: int64

In [12]:
test_x.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,9.0,0.31,0.48,6.6,0.043,11.0,73.0,0.99380,2.90,0.38,11.6,0
1,13.3,0.43,0.58,1.9,0.070,15.0,40.0,1.00040,3.06,0.49,9.0,1
2,6.5,0.28,0.27,5.2,0.040,44.0,179.0,0.99480,3.19,0.69,9.4,0
3,7.2,0.15,0.39,1.8,0.043,21.0,159.0,0.99480,3.52,0.47,10.0,0
4,6.8,0.26,0.26,2.0,0.019,23.5,72.0,0.99041,3.16,0.47,11.8,0

4. LightGBM 모델을 생성 및 훈련합니다.

In [13]:
model = lgbm.LGBMClassifier()
model.fit(train_x,train_y)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000241 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1538
[LightGBM] [Info] Number of data points in the train set: 5497, number of used features: 12
[LightGBM] [Info] Start training from score -5.353861
[LightGBM] [Info] Start training from score -3.386211
[LightGBM] [Info] Start training from score -1.123105
[LightGBM] [Info] Start training from score -0.822089
[LightGBM] [Info] Start training from score -1.783246
[LightGBM] [Info] Start training from score -3.588077
[LightGBM] [Info] Start training from score -7.002520
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier()

5. 생성한 모델로 예측 데이터를 생성합니다.

In [14]:
y_pred = model.predict(test_x)

6. 제출파일을 생성합니다.

In [21]:
#서브미션 파일의 quality 변수에 예측값을 대입합니다.
smpl_sub.head()

   index  quality
0      0        0
1      1        0
2      2        0
3      3        0
4      4        0

In [22]:
head(smpl_sub)

NameError: name 'head' is not defined

In [23]:
# csv 파일로 저장합니다.
smpl_sub.to_csv('submission.csv', index=False)

# 2. XGBoost

In [43]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3i4n1QB'

zsh:1: command not found: wget

In [25]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
from xgboost import XGBClassifier

train = pd.read_csv('/Users/seomichelle/26-1 ESAA:Python/datasets/와인/train.csv')
test = pd.read_csv('/Users/seomichelle/26-1 ESAA:Python/datasets/와인/test.csv')

train.drop('index',axis = 1 ,inplace =True)
test.drop('index',axis = 1 ,inplace =True)

In [26]:
# 데이터 확인
train.head()

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

In [27]:
# 원핫 인코딩 (pd.get_dummies())

import pandas as pd
from sklearn.preprocessing import LabelEncoder

train_one = pd.get_dummies(data = train, columns = ['type'], prefix = ['type'])

test_one = pd.get_dummies(data = test, columns = ['type'], prefix = ['type'])

encoder = LabelEncoder()
train_one['quality'] = encoder.fit_transform(train_one['quality'])

train_one.head()

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type_red,type_white
0,2,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,False,True
1,2,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,True,False
2,2,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,False,True
3,3,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,False,True
4,3,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,False,True

In [28]:
# 모델 정의
model = XGBClassifier()

In [29]:
# 모델 학습
# X 는 train에서 quality 를 제외한 모든 변수
# y 는 train의 qulity 변수
X = train_one.drop('quality',axis= 1)
y = train_one['quality']

# fit 메소드를 이용해 모델 학습
model.fit(X,y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [41]:
# predict 메소드와 원핫 인코딩한 test 데이터를 이용해 품질 예측
pred = model.predict(test_one)
pred

array([2, 2, 3, 2, 3, 3, 3, 3, 3, 4, 3, 3, 4, 3, 2, 2, 3, 3, 2, 3, 3, 3,
       2, 4, 3, 2, 2, 2, 2, 2, 4, 3, 2, 3, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3,
       3, 4, 2, 4, 1, 3, 2, 2, 3, 1, 2, 3, 3, 2, 2, 3, 2, 3, 3, 1, 3, 3,
       2, 2, 3, 2, 2, 2, 2, 3, 3, 2, 3, 3, 3, 4, 3, 3, 2, 1, 3, 3, 2, 3,
       4, 4, 3, 3, 3, 3, 3, 4, 3, 4, 3, 3, 2, 3, 3, 2, 2, 3, 3, 3, 4, 2,
       3, 3, 3, 2, 2, 3, 3, 4, 4, 3, 3, 2, 3, 3, 2, 2, 2, 3, 3, 4, 2, 2,
       3, 2, 2, 3, 3, 4, 2, 2, 2, 3, 2, 2, 2, 2, 4, 3, 4, 3, 2, 5, 3, 2,
       3, 2, 2, 2, 3, 2, 2, 3, 3, 4, 3, 2, 2, 3, 2, 3, 2, 2, 3, 2, 3, 3,
       3, 2, 2, 3, 3, 3, 4, 4, 2, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 3, 2,
       3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 4, 2, 2, 2, 3, 3, 3, 2, 3, 4,
       3, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3,
       3, 2, 4, 3, 3, 3, 2, 4, 2, 3, 3, 4, 3, 3, 3, 4, 3, 3, 4, 3, 2, 4,
       2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 3, 2, 4, 4, 2, 3, 3, 3, 3, 3, 4, 4,
       3, 3, 3, 3, 2, 2, 2, 3, 2, 4, 5, 3, 2, 5, 3, 3, 2, 2, 3, 4, 2, 4,
       2, 2, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3, 2, 2, 3, 2, 1, 2, 2, 3, 3, 2,
       2, 3, 3, 2, 2, 4, 2, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 2, 3, 2, 3,
       2, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 4, 3, 3, 2, 2, 3, 3, 3, 3, 2, 2,
       3, 2, 2, 3, 3, 3, 4, 3, 4, 3, 2, 3, 3, 2, 3, 3, 3, 2, 4, 3, 2, 3,
       3, 3, 4, 2, 4, 3, 3, 3, 4, 2, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3,
       2, 3, 4, 3, 2, 3, 2, 3, 3, 3, 2, 3, 4, 3, 2, 3, 5, 1, 3, 2, 2, 2,
       2, 4, 3, 2, 3, 3, 2, 2, 2, 3, 3, 4, 2, 3, 3, 3, 4, 2, 3, 2, 2, 3,
       2, 3, 2, 3, 3, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 5, 4, 3, 3, 4, 3, 2,
       5, 2, 2, 3, 2, 3, 3, 3, 2, 4, 2, 3, 3, 2, 3, 3, 3, 3, 3, 4, 3, 2,
       3, 3, 3, 4, 2, 2, 3, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 4, 3, 2, 4, 3,
       3, 3, 2, 2, 3, 2, 3, 4, 3, 3, 2, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3, 4,
       3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, 4, 3, 2, 3, 3,
       2, 4, 3, 2, 3, 2, 2, 2, 4, 3, 2, 2, 3, 4, 4, 4, 2, 4, 4, 2, 4, 3,
       2, 2, 3, 4, 3, 3, 3, 3, 3, 4, 2, 3, 2, 2, 4, 2, 5, 2, 4, 3, 3, 4,
       2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 2, 2, 3, 2, 3, 2, 2, 4, 2, 3,
       5, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 4, 3, 2, 3, 3, 3, 2,
       4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 4, 4, 2, 3, 3, 4, 4, 4, 3,
       4, 2, 3, 5, 3, 4, 2, 3, 4, 2, 2, 3, 3, 3, 3, 3, 2, 3, 4, 2, 3, 2,
       3, 3, 2, 3, 2, 2, 2, 2, 3, 2, 4, 3, 2, 3, 3, 3, 2, 3, 5, 2, 2, 3,
       3, 1, 4, 3, 2, 4, 2, 2, 4, 3, 2, 4, 3, 2, 3, 2, 3, 2, 3, 3, 4, 3,
       3, 2, 3, 2, 3, 3, 3, 4, 2, 3, 3, 3, 2, 2, 3, 4, 3, 3, 2, 3, 2, 3,
       2, 2, 3, 2, 3, 3, 3, 2, 3, 2, 4, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2,
       3, 3, 4, 3, 3, 2, 3, 2, 2, 2, 3, 3, 2, 4, 2, 4, 3, 3, 3, 3, 2, 4,
       4, 2, 3, 3, 3, 2, 3, 2, 3, 2, 5, 3, 3, 2, 4, 3, 3, 3, 3, 3, 4, 3,
       2, 4, 2, 2, 2, 3, 3, 3, 3, 2, 4, 4, 4, 3, 2, 4, 2, 3, 2, 3, 3, 3,
       2, 3, 2, 3, 4, 2, 3, 3, 2, 4, 2, 3, 4, 4, 3, 3, 2, 2, 3, 3, 3, 3,
       1, 3, 2, 2, 2, 4, 2, 3, 4, 2, 2, 3, 3, 2, 2, 2, 3, 3, 3, 4, 3, 3,
       2, 3, 3, 3, 3, 4, 2, 3, 3, 3, 2, 3, 3, 5, 4, 3, 2, 2, 3, 3, 3, 3,
       4, 2, 3, 2, 3, 3, 2, 2, 3, 3, 2, 2, 2, 3, 1, 3, 2, 3, 3, 2, 5, 3,
       3, 3, 3, 3, 3, 5, 3, 3, 2, 4, 3, 3, 3, 3, 2, 2, 2, 2, 3, 2, 2, 2,
       2, 4, 3, 3, 4, 3, 3, 2, 4, 4, 3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 2,
       3, 3, 3, 3, 4, 3, 2, 2, 3, 3])

In [ ]:
# sample_submission.csv 파일을 불러와 예측된 값으로 채워 주기
submission = pd.read_csv('/Users/seomichelle/26-1 ESAA:Python/datasets/와인/sample_submission.csv')
submission['quality'] = pred + 3ㅇ
submission.head()

   index  quality
0      0        5
1      1        5
2      2        6
3      3        5
4      4        6

In [32]:
# 정답파일 내보내기
submission.to_csv('xgb_pred.csv',index = False)

# 3. 보팅

In [42]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3i4n1QB'

zsh:1: command not found: wget

In [34]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

train = pd.read_csv('/Users/seomichelle/26-1 ESAA:Python/datasets/와인/train.csv')
test = pd.read_csv('/Users/seomichelle/26-1 ESAA:Python/datasets/와인/test.csv')

train.drop('index',axis = 1 ,inplace =True)
test.drop('index',axis = 1 ,inplace =True)

In [35]:
# 데이터 확인
train.head()

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

In [36]:
# 원핫 인코딩 (pd.get_dummies())
train_one = pd.get_dummies(train)
test_one = pd.get_dummies(test)

In [37]:
# 모델 정의 (LightGBM, XGBoost, Random Forest)
LGBM = LGBMClassifier()
XGB = XGBClassifier()
RF = RandomForestClassifier()

# VotingClassifier 정의
VC = VotingClassifier(estimators=[('rf',RF),('xgb',XGB),('lgbm',LGBM)],voting = 'soft')

In [38]:
import sys
!{sys.executable} -m pip install --upgrade xgboost

Requirement already satisfied: xgboost in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.2.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from xgboost) (2.4.2)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from xgboost) (1.17.1)

In [39]:
# 모델 학습

# X 는 train에서 quality 를 제외한 모든 변수
# y 는 train의 qulity 변수

X = train_one.drop('quality',axis= 1)
y = train_one['quality']

# fit 메소드를 이용해 모델 학습
VC.fit(X,y)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000474 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1540
[LightGBM] [Info] Number of data points in the train set: 5497, number of used features: 13
[LightGBM] [Info] Start training from score -5.353861
[LightGBM] [Info] Start training from score -3.386211
[LightGBM] [Info] Start training from score -1.123105
[LightGBM] [Info] Start training from score -0.822089
[LightGBM] [Info] Start training from score -1.783246
[LightGBM] [Info] Start training from score -3.588077
[LightGBM] [Info] Start training from score -7.002520
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

VotingClassifier(estimators=[('rf', RandomForestClassifier()),
                             ('xgb',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric=None,
                                            feature_types=None,
                                            feature_weights=None, gamma=None,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=None,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=None, n_jobs=None,
                                            num_parallel_tree=None, ...)),
                             ('lgbm', LGBMClassifier())],
                 voting='soft')

In [40]:
# predict 메소드와 원핫 인코딩한 테스트 데이터를 이용해 품질 예측
VC.predict(test_one)

array([5, 5, 6, 5, 6, 6, 6, 6, 6, 7, 6, 6, 7, 6, 5, 5, 6, 6, 6, 6, 6, 6,
       5, 7, 6, 5, 5, 5, 5, 5, 7, 6, 5, 6, 6, 6, 5, 5, 6, 6, 6, 5, 6, 6,
       6, 7, 5, 7, 4, 6, 5, 5, 6, 4, 5, 6, 6, 5, 5, 6, 5, 6, 6, 4, 6, 6,
       5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 6, 6, 6, 7, 6, 6, 5, 4, 6, 6, 5, 5,
       6, 7, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 7, 5,
       6, 6, 6, 5, 5, 6, 6, 7, 7, 6, 6, 5, 6, 6, 5, 5, 5, 6, 6, 7, 6, 5,
       6, 5, 5, 6, 6, 7, 5, 5, 5, 6, 5, 5, 5, 5, 7, 6, 7, 6, 5, 8, 6, 5,
       6, 5, 5, 5, 6, 5, 5, 6, 6, 7, 6, 5, 5, 6, 5, 6, 5, 5, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 7, 7, 5, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 7, 5,
       5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 7, 5, 5, 6, 6, 6, 5, 6, 6, 7,
       6, 5, 6, 6, 7, 6, 6, 5, 6, 5, 6, 7, 7, 6, 6, 6, 6, 6, 6, 7, 6, 6,
       6, 6, 7, 6, 6, 6, 6, 6, 5, 6, 7, 7, 6, 6, 6, 7, 7, 6, 7, 5, 5, 7,
       5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6, 5, 7, 7, 5, 6, 6, 6, 6, 6, 7, 7,
       6, 6, 6, 6, 5, 5, 5, 6, 5, 7, 8, 5, 5, 7, 6, 6, 5, 5, 6, 7, 5, 7,
       5, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 4, 5, 5, 6, 6, 5,
       5, 6, 7, 5, 5, 6, 5, 6, 6, 6, 5, 6, 7, 6, 5, 6, 6, 6, 5, 6, 5, 6,
       5, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 7, 7, 6, 5, 5, 6, 6, 6, 6, 5, 5,
       6, 5, 5, 6, 6, 6, 7, 6, 7, 6, 5, 6, 6, 5, 6, 6, 7, 5, 7, 6, 5, 6,
       6, 7, 7, 5, 7, 6, 6, 6, 7, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 6, 7, 6, 5, 6, 6, 6, 6, 6, 5, 6, 7, 6, 5, 6, 6, 4, 6, 5, 5, 5,
       5, 7, 6, 5, 6, 6, 5, 5, 5, 6, 6, 7, 5, 6, 6, 6, 7, 5, 6, 5, 5, 6,
       5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 8, 7, 6, 6, 7, 5, 5,
       8, 5, 5, 6, 5, 6, 6, 6, 5, 7, 5, 6, 6, 5, 6, 6, 6, 6, 6, 7, 6, 5,
       6, 7, 6, 7, 6, 5, 6, 6, 6, 5, 5, 7, 6, 5, 5, 5, 5, 7, 6, 5, 7, 6,
       6, 6, 5, 5, 6, 5, 6, 6, 6, 6, 4, 5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 7,
       6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 7, 6, 6, 7, 6, 5, 6, 6,
       5, 7, 6, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 7, 7, 7, 5, 7, 7, 5, 7, 6,
       5, 5, 5, 7, 6, 6, 6, 6, 6, 7, 5, 6, 5, 5, 7, 5, 8, 5, 6, 6, 6, 6,
       5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 7, 5, 6,
       8, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 7, 6, 5, 6, 6, 6, 5,
       7, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 7, 5, 5, 6, 6, 7, 7, 7, 6,
       7, 5, 6, 8, 6, 6, 5, 6, 7, 5, 5, 6, 6, 6, 6, 6, 5, 6, 7, 5, 6, 5,
       5, 6, 5, 6, 5, 5, 5, 5, 6, 5, 7, 6, 5, 6, 6, 6, 5, 6, 8, 5, 5, 6,
       6, 4, 7, 6, 5, 7, 5, 5, 7, 6, 5, 7, 6, 5, 6, 5, 6, 5, 6, 6, 7, 6,
       6, 5, 6, 5, 6, 6, 6, 7, 5, 7, 6, 6, 5, 5, 6, 7, 6, 6, 5, 6, 5, 6,
       5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 7, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6,
       6, 6, 7, 6, 6, 5, 6, 5, 5, 5, 6, 6, 5, 6, 5, 7, 7, 6, 6, 6, 5, 7,
       7, 5, 6, 6, 6, 5, 6, 5, 5, 5, 8, 6, 6, 5, 7, 6, 6, 6, 6, 6, 7, 6,
       5, 7, 5, 5, 5, 6, 6, 5, 6, 5, 7, 7, 7, 6, 5, 7, 5, 6, 5, 6, 6, 6,
       5, 6, 5, 6, 5, 5, 6, 6, 5, 7, 5, 6, 7, 7, 7, 6, 5, 5, 6, 6, 6, 6,
       5, 6, 5, 5, 5, 7, 5, 6, 7, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6, 7, 6, 6,
       5, 7, 6, 6, 5, 7, 5, 6, 6, 6, 5, 6, 6, 8, 7, 6, 5, 5, 6, 6, 6, 6,
       7, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 5, 6, 4, 6, 5, 6, 6, 5, 8, 6,
       6, 5, 6, 6, 6, 8, 6, 6, 5, 7, 6, 7, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5,
       5, 7, 6, 6, 7, 6, 6, 5, 7, 6, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 5, 6, 6])